version: "3"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER:root
      - MYSQL_PASSWORD:root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mahdi5NIDS2
    volumes:
      - db_vol:/var/lib/mysqldb

  departement_app:
    build: ./
    image: mahdi
    restart: unless-stopped
    ports:
      - 8089:8089
    depends_on:
      - mysqldb


volumes:
  db_vol:
